version: "3.9"

services:

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "host.docker.internal:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "host.docker.internal:2181"

    