const USER_AUTHENTICATED = "USER_AUTHENTICATED";
const USER_UNAUTHENTICATED = "USER_UNAUTHENTICATED";
const USER_AUTH_ERROR = "USER_AUTH_ERROR";
const USER_AUTH_LOADING = "USER_AUTH_LOADING";


export {
    USER_AUTHENTICATED,
    USER_UNAUTHENTICATED,
    USER_AUTH_ERROR,
    USER_AUTH_LOADING,
}
