-- CREATE TABLE USERS (
--     ID SERIAL PRIMARY KEY,
--     USERNAME VARCHAR(255) NOT NULL,
--     AGE INT NOT NULL
-- );

DROP TABLE USERS;

-- INSERT INTO USERS (USERNAME, AGE) VALUES ('Ravi', 20);

-- SELECT * FROM USERS;