-- INSERT INTO USERS (EMAIL, NAME, LOCATION)
-- VALUES ('john@gmail.com', 'John', DEFAULT) ON CONFLICT (EMAIL) DO UPDATE
-- SET EMAIL = NULL;

INSERT INTO USERS 
VALUES ('john@gmail.com','John', DEFAULT) ON CONFLICT (EMAIL) DO UPDATE
SET EMAIL = NULL;