version: "3"

services:
  web:
    image: hello-docker-web:latest
    ports:
      - "8000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/database
    entrypoint: ["npm", "run", "start"]
    networks:
      - web-network
    depends_on:
      - db

  db:
    image: mongo:latest
    networks:
      - web-network
    command: mongod

networks:
  web-network:
    driver: bridge
