DROP TABLE USERS;

-- CREATE TABLE USERS (
--     ID SERIAL PRIMARY KEY,
--     NAME VARCHAR,
--     AGE INT
-- );

-- DROP TABLE USERS;

-- INSERT INTO USERS 
-- (NAME, AGE) 
-- VALUES ('Teena', 28);

-- SELECT ID, NAME, AGE FROM USERS;