import SideDrawer from "@/components/SideDrawer";
import "../globals.css";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import CustomAppBar from "@/components/CustomAppBar";
import { Suspense } from "react";
import Redirect from "@/components/Redirect";
import AddPostFab from "@/components/AddPostFab";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies();

  console.log(cookieStore.get("access-token"));

  const response = await fetch("http://localhost:5000/v1/users/me", {
    headers: {
      authorization: `Bearer ${cookieStore.get("access-token").value}`,
    },
  });

  if (response.status !== 200) {
    return (
      <Suspense
        fallback={
          <div
            style={{
              width: "100vw",
              height: "100vh",
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            Redirecting to Login...
          </div>
        }
      >
        <Redirect to="/login" />
      </Suspense>
    );
  }

  const user = await response.json();

  return (
    <div
      style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        width: "100vw",
        height: "100vh",
      }}
    >
      <CustomAppBar user={user} />
      <SideDrawer />
      {children}
    </div>
  );
}
