import SideDrawer from "@/components/SideDrawer";
import "../globals.css";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import CustomAppBar from "@/components/CustomAppBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies();

  console.log(cookieStore.get("access-token"));

  const response = await fetch("http://localhost:5000/v1/users/me", {
    headers: {
      authorization: `Bearer ${cookieStore.get("access-token").value}`,
    },
  });

  const user = await response.json();

  return (
    <html lang="en">
      <body className={inter.className}>
        <CustomAppBar user={user} />
        <SideDrawer />
        {children}
      </body>
    </html>
  );
}
